name: vimrc

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pip install -U setuptools
        pip install vim-vint
    - name: Lint
      run: /usr/local/bin/vint vim/*.vim
