name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pip3 install -U setuptools 
        pip3 install vim-vint
        export PATH="$PATH:/usr/local/lib"
    - name: Lint vimscript
      run: vint vim/*.vim
