name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        pip3 install -U setuptools 
        pip3 install vim-vint
        ls /usr/local/lib/
        echo $(which vint)
    - name: Lint vimscript
      run: /usr/local/lib/vint vim/*.vim
